# Generated by Django 5.0.7 on 2024-07-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('female_healthcare_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='Longitude',
        ),
    ]
