# Generated by Django 5.0.7 on 2024-07-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('female_healthcare_management', '0002_rename_address_doctors_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='address',
            field=models.TextField(),
        ),
    ]
