# Generated by Django 5.0.7 on 2024-07-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('female_healthcare_management', '0005_remove_doctor_description_doctor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
