name: First CICD using GitHub Actions
on:   
  push:
   branches:
     - main
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
       - name: Code Checkout
         uses: actions/checkout@v4.1.7

       - name: Install Python
         uses: actions/setup-python@v5.1.1
         with:
          python-version: 3.11

       - name: Install Dependencies
         run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt 

       - name: Running Python
         run: |
           python manage.py runserver
