name: First CICD using GitHub Actions

on:   
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Corrected to use a hyphen

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4  # Simplified to use the latest v4 version

      - name: Install Python
        uses: actions/setup-python@v5  # Simplified to use the latest v5 version
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Running Django Tests  # It's better to run tests instead of the server
        run: |
          python manage.py test
